baseURL = "https://vorthosmine.online/"
languageCode = "en-us"
title = "Vorthos Mine"
theme = "mainroad"
ignoreFiles = [
    "\\.Rmd$",
    "\\.Rmarkdown$",
    "_cache$",
    "\\.knit\\.md$",
    "\\.utf8\\.md$",
]

[Author]
name = "Tyler W. Davis"
bio = "Engineer, educator, dream weaver, plus coder."
avatar = "danger.png"

[Params]
description = "Alternative deck building for Magic: The Gathering"
opengraph = true
twitter_cards = false
readmore = false
authorbox = true
pager = true
post_meta = ["date", "categories"]
mainSections = ["post", "docs"]

[Params.logo]
image = "logo.png"
subtitle = "Alternative EDH deckbuilding"

[Params.sidebar]
home = "right"
list = "right"
single = "right"
# Enable widgets in given order
widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
recent_num = 5 # Set the number of articles in the "Recent articles" widget
tags_counter = true # Enable counter for each tag in "Tags" widget

[permalinks]
post = "/:year/:month/:day/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
