---
title: "The Neverending Story Cartoon Notes"
description: "Show notes taken while watching The Neverending Story cartoon."
draft: true
tags:
  - "Story Notes"
  - "Research"
---

[The Neverending Story][nes_cartoon] cartoon is a 26-episode series originally released in Canada in the mid 90s (by CineVox Entertainment), starring [Christopher Bell][imdb_c_bell] as the voice actor for Bastion Bux.
<!--more-->

There are some interesting ideas used throughout the show.
A few are noted here:

- Mr. Coreander never appears in character, only as a voice or is mentioned by other characters.
- The end of each episode utilizes the book's "and they went on to have many other adventures, but that's another story."

---

# Episode Summaries

## Episode 1 - The Tears of Sadness
Xyede poisons the Fountain of Life with the tears of the Acharis (human-sized zombie worms), but Barktroll uses a happy potion to reverse their sadness and turn them into Schlamoofs (i.e., the happiest creatures in Fantasia).

We are introduced to:

- Barktroll, a weird tree monster and side-kick of Bastion's
- Bighead (a replacement for Cairon, herald of the Childlike Empress)
- The Childlike Empress
- Engywook, the scientist
- Urgl, the potions master
- Xyede, the queen of emptiness
- Arachis, the worms whose tears make the Silver Sea


## Episode 2 - The Meek and the Mighty
Junior Rockchewer gets lost in the caves of Fantasia and Bastion and Gluckuk are sent in to the rescue.

We are introduced to:

- Gluckuk, the tiny and his racing snail
- Rockchewer (i.e., Pyornkrachzark, the rock biter) and family


## Episode 3 - The Purple Buffalo
Xyede plans to turn all the purple buffalo into giant locusts that will eat the grassy ocean in her effort to destroy Fantasia, but Bastion follows the advice of the Great Buffalo Spirit to counter her evil deeds.

> "The Horn of Gatylon, free the buffalo, use the powder, where there is life, there is always hope." -- The Great Buffalo Spirit

We are introduced to:

- Atreyu, the Greenskin warrior


## Episode 4 - Morla's Wish
Bastion takes Morla a wish box for her birthday from the Childlike Empress.

We learn that Morla is female.

We are introduced to:

- Jack-o (the birdman)
- Mud monsters
- Traitor of trinkets, treasures, and persons (shadow goblin)
- G'mork (wolfman)
- Morla, the ancient one


## Episode 5 - Spook City
Bastian and Gaia enter Spook City in order to rescue Gaia's brother, Mika, from the nothing and come face-to-face with their greatest fear.

> "What's a few more horrors where friends are concerned?" --- Barktroll

Characters, places, and quotes of interest:

- Spook City, the place of shadows, rests in the darkest corner of the Forbidden Forest
- Mystic Compass that takes exactly where you want to go and back again, but only once
- Necromancer, the creator of the compass
- Argax, the monkey with a walking stick
- The Nightwatchmen, eye ball monsters
- Hunger of the Wolfpack?


## Episode 6: To Save Falcor
Falcor picks up Bastion's cold while delivering medicine to Large Head's mother, causing Bastion to side quest to the Dead Mountains for Tarkus flowers and face off with Ygramul, the horror of horrors.

Introduces:

* One of the messengers (blue hooded)
* Vessel:  big sleepy bat
* Old Rosa (nighthawk and potion master)
* Tarkus flowers only grow on the tallest peak of the Dead Mountains
* Ygramul, the horror of horrors (big spider)


## Episode 7 - Missing Memories
Bastian travels to see the Southern Oracle when parts of Fantasia begin to disappear only to find that Xayide, Queen of Darkness, is mining the Empress's memories.

> "What is mine is yours." --- The Southern Oracle

Characters, places, and quotes of interest:

- Southern Oracle depicted as a pair of gold sphinxes facing each other
    * "we watch each other to keep each other company"
- you may only ask one question
- Oracle speaks only in riddles
- Gnomic Forest, where Engywook and Urgl
    * Engywook's flying machine, the Woogle monitor (Ornithopter of Paradise)
- Yur, the keeper of the mine of memories
    * The memories are the material out of which the whole underground of Fantasia is composed.
- Snow sprites
- Cheesy Wheezy Mountains


## Episode 8 - Perilin
When the Perilin Forest begins growing uncontrollably, Bastian and Bark Troll search out Grograman, the fire lion, who is held captive by Xayide in Horok Castle.

> "In Fantasia, there's a reason for everything" --- Falcor

- Perilin, the night forest was the most beautiful and breathtaking forest in Fantasia
- Grograman, the fire lion, Lord of Goebb, the desert of ever-changing color


## Episode 9 - The Sea of Mist
Engywook finds the ancient sea scrolls that hold all the lost secrets of Fantasia, which are stolen by pirates who sail to Isle of Sir Pumple Nuse, only to be lost again in the Sea of Mist (some secrets are best unknown).


## Episode 10 - Promises
Atreyu, Bastian, and Atreyu's younger sister, Saya, travel to the Canyon of Lies to destroy the the evil medicine man's magic staff before the shaman can wreak his vengeance on the Green skins.

A lesson on when it's okay to break promises.


## Episode 11 - Through the misty mountains
Bastion teams up with Big Head to confront the Monster of Misty Mountains that threatens the supply chain of Fantasia only to fail to work together.

Characters and places of interest:

- Moldy More (swamp)
- Glubb's the name, fun's the game (will-o-the-wisp)
- Wall Rocksy (four-legged walrus)
- Misty Mountains are snowcapped
- The Clumps (tiny flying fury things)


## Episode 12 - A friendship that flames
When Xayide's bird, Nimbly, steals a gift meant for the Childlike Empress, Bastion and Barktroll follow Axen (a blue badger entertainer) into thinking it's a mythic gubgub bird and travel to Fire Mountain to retrieve it.


## Episode 13 - The three feeling stones
Xayide steals the three feeling stones (hope, love, and joy) and becomes the new empress of Fantasia only to be bested by Urgl's love potion.


## Episode 14 - The invisibility belt
After Ghemmal is found by the wrong hands, Bastian seeks out Xayide to help him stop the Shadow Goblin from stealing all the treasure from Fantasia, only to fall into a perpetual fading to the void.

Characters and places of interest:

- Ghemmal, the belt of invisibility, gifted to Bastian by Xayide
- Barktrollville
- Bottomless Pit of Dandar


## Episode 15 - Good Deeds
Bastian has to use fairy powder to get him and Barktroll away from troublesome wolves while they "help" a travelling man deliver water to his village a second time after drinking it all during the first trip as their reward for doing a "good deed."

> "Oooh, sparkle stuff!" --- Barktroll


## Episode 16 - Barktroll's Blame
Bastian and the Night Hobs help Barktroll put out the fires in the Howling Forest during the Sap Jubilee after Barktroll takes the blame for starting them.

- The Sap Jubilee in the Howling Forest occurs once every thousand years
- Introduces:
    * other tree trolls (including trees with tits),
    * lumber loafers (British sounding big eared squirrels); oi' oi' oi',
    * flim-fams (New York sounding beavers that spin like Tasmanian devils)
    * tree toad (Conga line-dancing frog w/ maracas)
- Mentions "bearded fauns" and "soldier ants"

Lessons: don't pass judgement too soon on friends.


## Episode 17 - The Searcher
Engywook uses a lop's egg to unlock the Vault of Wisdom, but nearly crushes it in the process.

> "It sounded like all the sadness in the world." --- Falcor

- Key to the Vault of Wisdom
- "You less than perfect person!" -- Urgl
- "Perfumed mud blossom."
- Hot springs in the snow (land of cold fire)
- Lop (green polar bear)
- Snow kink

[imdb_c_bell]: https://www.imdb.com/name/nm0068110/
[nes_cartoon]: https://en.wikipedia.org/wiki/The_Neverending_Story_(TV_series)
