---
title: "Origin Story"
description: "A look at how this project got started."
date: 2022-04-01
authorbox: false
slug: "origin-story"
categories:
  - "Development"
tags:
  - "History"
---

"_I would like, if I may, to take you on a strange journey._"
<!--more-->

It's just a jump to the left.

And then a step to the right.

Actually, it all started a ways back when I was brewing my first commander decks.
These were Simic Merfolk versus Jeskai Flying Pingers.
My partner mentioned that their interest in the game was piqued by the theme.
As it turns out, most of the merfolk in _Magic: The Gathering_ are depicted as a bit scary.

I turned my attention to making a five-color fantasy knight-themed deck, which was conveniently aligned with the release of the _Throne of Eldraine_ set.
This deck ended up being torn apart and from it's pieces came my Naya fantasy deck, commanded by Marath, Will of the Wild.

Finally after a few more iterations of deck building, the theme of Harry Potter was proposed.
Someone on Instagram or Reddit had posted example cards that could match characters from the books and film franchise.
And so my first Vorthos Mine deck was born sometime in 2020.

My second Vorthos Mine deck was built on the remnants of the fantasy knight deck.